### ISSUE TITLE
I have a problem with CMake DBoW2.

### ISSUE THREAD

**Issue by SoonBeomKwon** [Phylliida/orbslam-windows#4]
I have a problem with CMake DBoW2.

> CMake Error at CMakeLists.txt:31 (message):
>   OpenCV > 2.4.3 not found.

When i do CMake DBoW2, this message come out.

I have a Visual Studio 2017 and OpenCV 3.0.0.

What should i do?

**Comment by devphilno** [comment]
You should add your OpenCV Directory to PATH

**Comment by Filimindji** [comment]
Hello there.

I have the same issue.

Can you provide more specific instruction please ?

Thank you

**Comment by Phylliida** [comment]
Try running the CMake gui and then it'll let you fill in the box that points to wherever you have OpenCV installed

**Comment by Filimindji** [comment]
It worked, thank you.

I fill the OPENCV_DIR box with the **build** subfolder of OpenCV (the one that contains OpenCVConfig.cmake file)
