### ISSUE TITLE
generated g2o.sln is empty

### ISSUE THREAD

**Issue by lizeyu000** [Phylliida/orbslam-windows#7]
When using CMake in the second step, cmake has some warnings:

### BUILD TYPE:Release
Try OpenMP C flag = [/openmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Success
CMake Warning (dev) at D:/Program Files/CMake/share/cmake-3.8/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  D:/Program Files/CMake/share/cmake-3.8/Modules/FindOpenMP.cmake:224 (_OPENMP_GET_SPEC_DATE)
  CMakeLists.txt:48 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

Try OpenMP CXX flag = [/openmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Success
CMake Warning (dev) at D:/Program Files/CMake/share/cmake-3.8/Modules/FindOpenMP.cmake:179 (if):
  if given arguments:

    "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
Call Stack (most recent call first):
  D:/Program Files/CMake/share/cmake-3.8/Modules/FindOpenMP.cmake:266 (_OPENMP_GET_SPEC_DATE)
  CMakeLists.txt:48 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

Found OpenMP: /openmp  
Found Eigen3: E:/LearnORBSLAM/Thirdparty/eigen (Required is at least version "3.1.0") 
Configuring done

and the generated SLN file can be opened. but VS shows that g2o does not contain any configuration, and can not be opened, so nothing is shown.

Thank you very much!

**Comment by Phylliida** [comment]
Umm this is perhaps a dumb suggestion but once it outputted "Configuring done", did you click the "Generate" button?

**Comment by lizeyu000** [comment]
Thank you very much. I just made a stupid mistake.
