### ISSUE TITLE
Problem with Pangolin

### ISSUE THREAD

**Issue by pscore30** [Phylliida/orbslam-windows#9]
Hi All,
I cannot build Pangolin. But i´m using Visual Studio 2015 to build it; may it be the problem?. The errors that i have are:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'pthread.lib'	testlog	D:\VSLAM\orbslam-windows\Thirdparty\Pangolin\build\test\log\LINK	1	
Error	C1189	#error:  Xiron Platform Abstraction Layer - Win32 - Microsoft Visual Studio versions above 2010 (10.0) are not supported!	pangolin	c:\program files\openni\include\XnPlatform.h	57	
`

**Comment by idxExtropy** [comment]
The instructions specifically say to ignore the 'pthread.lib' error.  It's fine..

`Build ALL_BUILD. You'll have an error by project testlog that says "cannot open input file 'pthread.lib'" but that doesn't matter cause we don't use testlog. Everything else should build fine, i.e., you should have ========== Build: 18 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`
